trigger:
- master

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'uniqueConnectionName'
    ScriptType: 'FilePath'
    ScriptPath: '$(Build.SourcesDirectory)/storageAccountsDeploy.ps1'
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'uniqueConnectionName'
    ScriptType: 'FilePath'
    ScriptPath: '$(Build.SourcesDirectory)/windowsDeploy.ps1'
    azurePowerShellVersion: 'LatestVersion'