trigger:
- master

pool:
  name: default

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'uniqueConnectionName'
    ScriptType: 'InlineScript'
    Inline: |
        $vmName = 'simple-vm'
        $resourceGroupName = 'WindowsRG'
        $command = 'az vm list-skus --resource-group $resourceGroupName --name $vmName'
        $vm = Get-AzVM -ResourceGroupName $resourceGroupName -Name $vmName
        $result = Invoke-AzVMRunCommand -ResourceGroupName $resourceGroupName -VMName $vmName -CommandId 'RunPowerShellScript' -ScriptPath $command

        Write-Host $result.Value[0].Message

- task: AzurePowerShell@5
  displayName: 'Deploy Windows'
  inputs:
    azureSubscription: 'uniqueConnectionName'
    ScriptType: 'FilePath'
    ScriptPath: '$(Build.SourcesDirectory)/windowsDeploy.ps1'
    azurePowerShellVersion: 'LatestVersion'