trigger:
- master

pool:
  name: default

steps:
- task: AzurePowerShell@5
  displayName: 'Create storage account'
  inputs:
    azureSubscription: 'uniqueConnectionName'
    ScriptType: 'FilePath'
    ScriptPath: '$(Build.SourcesDirectory)/scripts/storageAccountsDeploy.ps1'
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@5
  displayName: 'Deploy Windows'
  inputs:
    azureSubscription: 'uniqueConnectionName'
    ScriptType: 'FilePath'
    ScriptPath: '$(Build.SourcesDirectory)/scripts/windowsDeploy.ps1'
    azurePowerShellVersion: 'LatestVersion'
- task: AzurePowerShell@5
  displayName: 'Install Az-PS Module on the VM'
  inputs:
    azureSubscription: 'uniqueConnectionName'
    ScriptType: 'FilePath'
    ScriptPath: '$(Build.SourcesDirectory)/scripts/installAndConnectAz.ps1'
    azurePowerShellVersion: 'LatestVersion'
- task: AzurePowerShell@5
  displayName: 'Create and copy 100 blobs'
  inputs:
    azureSubscription: 'uniqueConnectionName'
    ScriptType: 'FilePath'
    ScriptPath: '$(Build.SourcesDirectory)/scripts/invokeCreateCopyBlobs.ps1'
    azurePowerShellVersion: 'LatestVersion'
